### ISSUE TITLE
'is_inpainting_task': 'inpainting' in model.name_or_path

### ISSUE THREAD

**Issue by crapthings** [megvii-research/HiDiffusion#26]
Traceback (most recent call last):
  File "/home/zznet/workspace/ai-pipe/prod-ai-pipe-replace-model/runpod_app.py", line 14, in <module>
    from pipe import text2img, getText2imgPipe, set_sampler, compel
  File "/home/zznet/workspace/ai-pipe/prod-ai-pipe-replace-model/pipe.py", line 34, in <module>
    apply_hidiffusion(text2imgPipe)
  File "/home/zznet/.local/lib/python3.10/site-packages/hidiffusion/hidiffusion.py", line 1959, in apply_hidiffusion
    'is_inpainting_task': 'inpainting' in model.name_or_path,
TypeError: argument of type 'NoneType' is not iterable

**Comment by ShenZhang-Shin** [comment]
Do you run inpainting following the code in readme? Or you use your own code

**Comment by minipuding** [comment]
I have the same problem

**Comment by ShenZhang-Shin** [comment]
You can check whether model is  NoneType. Or can you show your code?

**Comment by iwr-redmond** [comment]
Same error here.

Code snippets:
```
base_model_id='/var/storage/checkpoints/0001softrealistic_v187xxx.safetensors'

self.pipe = StableDiffusionPipeline.from_single_file(
                        base_model_id,
                        torch_dtype=self.type_model_precision,
                    )
                    class_name = "StableDiffusionPipeline"

apply_hidiffusion(self.pipe)
```

diffusers==0.29.0

**Comment by JohnnyStreet** [comment]
A solution was already posted here but never added to the repo https://github.com/megvii-research/HiDiffusion/issues/3
